# -*- coding: utf-8 -*-
"""day5 filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BzcdpBAuAREArZ83qXaFoWuSKWiI50YE
"""

#Use filter function to filter out the elements from a list that are divisible by 3 & 5

yogesh= list(range(1,50))
  
result3 = list(filter(lambda x: (x % 3 == 0), yogesh)) 
result5 = list(filter(lambda x: (x % 5 == 0), yogesh)) 
  
print("This number only divisible by 3 in 1-50 numbers : \n",result3) 
print("This number only divisible by 5 in 1-100 number : ",result5)

