# -*- coding: utf-8 -*-
"""multipleinsum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BzcdpBAuAREArZ83qXaFoWuSKWiI50YE
"""

# Take multiple numbers as input and print the sum
# 10 20 30 
x = [int(i) for i in input('Enter integer values: ').split()]

s = 0
for j in x:
  s += j # sum = sum + j

print(s)