# -*- coding: utf-8 -*-
"""Value is maximum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BzcdpBAuAREArZ83qXaFoWuSKWiI50YE
"""

# From a dictionary, print the Key whose Value is maximum in the dictionary.

names={"India":100,"USA":90,"UK":78}
max=0
str=""
for i in names:
    for j in i:
        if names [i] > max:
            str=i
            max= names[i]
print(str)

